---

- name: Instalando PHP
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - php7.0-json
    - php7.0-mbstring
    - php7.0-intl
    - php7.0-xml
    - php7.0-mysql
    - libapache2-mod-php7.0
    - git

- name: Instalar Apache y dependencias
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make
    - perl
    - apache2

- name: apache2 service state
  service: name=apache2 state=started enabled=yes
