---

- name: Descargando y extrayendo mediawiki
  unarchive:
      src: "{{ url }}"
      dest: /opt/
      list_files: yes
      remote_src: yes

- name: Incluyendo mediawiki a apache
  command: cp -R -u {{ path }} {{ apache_path }}

- name: Añadiendo configuraciones de MediaWiki
  template:
    src: LocalSettings.php.j2
    dest: "{{ media_config_file }}"
  notify:
    - restart apache
