---
# tasks file for nosqlserver



- name: Actualizar todos los packetes a la ultima version
  apt:
    upgrade: dist

- name:  contraseña root para MySQL
  debconf:
   name: mysql-server
   question: mysql-server/root_password
   value: 123456
   vtype: password

- name: Confirmando contraseña root de MySQL
  debconf:
   name: mysql-server
   question: mysql-server/root_password_again
   value: 123456
   vtype: password
       
- name: Instalar MySQL
  apt: package={{ item }} state=installed force=yes update_cache=yes cache_valid_time=3600
  when: ansible_os_family == 'Debian'
  with_items:
     - mysql-server
     - mysql-client
     - python-mysqldb
     
     
- name: Añadiendo configuracion
  template:
   src: mysqld.cnf.j2
   dest: /etc/mysql/mysql.conf.d/mysqld.cnf
   owner: root
   group: root
   mode: 0644

- name: Habilitando servicio Mysql al inicio del host
  service: name=mysql state=started enabled=yes

- name: Creando base de datos mediawiki
  mysql_db:
    login_user: root
    login_password: 123456
    name: "mediawiki"
    state: present
   
- name: creando usuario para la BD
  mysql_user: login_user=root login_password=123456  name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
   

          
- name: Iniciar servicio Mysql
  service: name=mysql state=started
